set -x
GO111MODULE=on
go get -u -v golang.org/x/crypto/...
go get -u -v golang.org/x/tools/...
go get -u -v golang.org/x/net/... 
go get -u -v golang.org/x/sys/... 
go get -u -v golang.org/x/text/...
go get -u golang.org/x/image/... 

